#!/bin/bash

TOKEN_ADDRESSES=$1
NETWORK_NAME=$2

if [ "${TOKEN_ADDRESSES}" == "" ]; then
        echo "You need to specify at least one token address."
        exit 1
fi

if [ "${NETWORK_NAME}" == "" ]; then
        NETWORK_NAME="regtest"
fi

cat > allowTokens.js << EOF

async function getRevertReason(txHash) {
  const tx = await web3.eth.getTransaction(txHash);
  const txBlockNumber = tx.blockNumber;
  try {
    delete tx['hash'];
    delete tx['blockHash'];
    delete tx['blockNumber'];
    delete tx['transactionIndex'];
    delete tx['v'];
    delete tx['r'];
    delete tx['s'];
    let result = await web3.eth.call(tx, txBlockNumber);
    result = result.startsWith('0x') ? result : '0x' + result;
    if (result && result.substr(138)) {
      return web3.utils.toAscii(result.substr(138));
    } else {
      return 'Cannot get reason - No return value';
    }
  } catch (reason) {
    return reason;
  }
}

module.exports = async function( ) {
  const contractAddresses = require('./contract-addresses.json');
  const smartWalletDeployVerifierAbi = require("./build/contracts/DeployVerifier.json").abi;
  const customSmartWalletDeployVerifierAbi = require("./build/contracts/CustomSmartWalletDeployVerifier.json").abi;
  const relayVerifierAbi = require("./build/contracts/RelayVerifier.json").abi;

  const smartWalletDeployVerifier = await new web3.eth.Contract(smartWalletDeployVerifierAbi, contractAddresses["${NETWORK_NAME}"].smartWalletDeployVerifier);
  const smartWalletRelayVerifier = await new web3.eth.Contract(relayVerifierAbi, contractAddresses["${NETWORK_NAME}"].smartWalletRelayVerifier);
  const customSmartWalletDeployVerifier = await new web3.eth.Contract(customSmartWalletDeployVerifierAbi, contractAddresses["${NETWORK_NAME}"].customSmartWalletDeployVerifier);
  const customSmartWalletRelayVerifier = await new web3.eth.Contract(relayVerifierAbi, contractAddresses["${NETWORK_NAME}"].customSmartWalletRelayVerifier);

  const tokenAddresses = '${TOKEN_ADDRESSES}'.split(',');

  const accounts = await web3.eth.getAccounts();

  try {
    for (let tokenAddress of tokenAddresses) {
      try {
        await smartWalletDeployVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
      } catch (error) {
        const reason = error.hasOwnProperty('receipt') ? await getRevertReason(error.receipt.transactionHash) : error;
        console.error("Error adding token with address " + tokenAddress + " to allowed tokens on smart wallet deploy verifier", reason);
        throw error;
      }
      try {
        await smartWalletRelayVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
      } catch (error) {
        const reason = error.hasOwnProperty('receipt') ? await getRevertReason(error.receipt.transactionHash) : error;
        console.error("Error adding token with address " + tokenAddress + " to allowed tokens on smart wallet relay verifier", reason);
        throw error;
      }
      try {
        await customSmartWalletDeployVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
      } catch (error) {
        const reason = error.hasOwnProperty('receipt') ? await getRevertReason(error.receipt.transactionHash) : error;
        console.error("Error adding token with address " + tokenAddress + " to allowed tokens on custom smart deploy verifier", reason);
        throw error;
      }
      try {
        await customSmartWalletRelayVerifier.methods.acceptToken(tokenAddress).send({from: accounts[0]});
      } catch (error) {
        const reason = error.hasOwnProperty('receipt') ? await getRevertReason(error.receipt.transactionHash) : error;
        console.error("Error adding token with address " + tokenAddress + " to allowed tokens on custom smart wallet relay verifier", reason);
        throw error;
      }
    }
  } catch (error) {
    console.error(error);
    console.error("Failed to allow tokens");
    return;
  }
  console.log("Tokens allowed successfully!");
}
EOF

truffle exec --network ${NETWORK_NAME} allowTokens.js

rm allowTokens.js
