#!/bin/bash

if [ $# -eq 0 ]; then
        echo "You need to specify the network to use for deploy, should be one inside of the truffle.js file."
        exit 1
fi

NETWORK=$1

npx truffle migrate --network "${NETWORK}"
