#!/bin/bash

SWITCH=$1

if [ "${SWITCH}" == "enable" ]; then
  pinst --enable
elif [ "${SWITCH}" == "disable" ]; then
  pinst --disable
else
  echo "Error: use enable or disable as argument."
  exit 1
fi

