#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -d "$HOME/.nvm" ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

npx prettier --check .
npm run lint:ts:fix
npm run lint:sol
